### ISSUE TITLE
RawInputStream: Invalid number of channels [PaErrorCode -9998]

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-microphone-plugin-sounddevice#3]
When starting `ovos-dinkum-listener` service,
```
2023-05-26 17:49:04.274 - OVOS - ovos_microphone_plugin_sounddevice:start:56 - DEBUG - Opening microphone (rate=16000, width=2, channels=1)
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
2023-05-26 17:49:04.280 - OVOS - ovos_dinkum_listener.service:run:272 - ERROR - Service failed to start
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 247, in run
    self._start()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 288, in _start
    self.mic.start()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_microphone_plugin_sounddevice/__init__.py", line 68, in start
    self.stream = sd.RawInputStream(
                  ^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/sounddevice.py", line 1192, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='buffer',
  File "/home/ovos/.venv/lib/python3.11/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/home/ovos/.venv/lib/python3.11/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening RawInputStream: Invalid number of channels [PaErrorCode -9998]
2023-05-26 17:49:04.304 - OVOS - ovos_dinkum_listener.service:on_error:66 - ERROR - DinkumVoiceService failed to launch (Error opening RawInputStream: Invalid number of channels [PaErrorCode -9998]).
```

**Comment by goldyfruit** [comment]
Fixed by https://github.com/OpenVoiceOS/ovos-microphone-plugin-sounddevice/commit/9f2d3f623ec948d9022b44dea2b7d825d10a77c1
